### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by hiredgunhouse** [luminus-framework/guestbook#27]
I have cloned the repo and tried `lein run` but I get an error on startup:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalArgumentException: Must hint overloaded https://github.com/luminus-framework/guestbook.gitmethod: toArray, compiling:(flatland/ordered/set.clj:19:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6319)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.eval(Compiler.java:6924)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$use.invokeStatic(core.clj:5860)
	at clojure.core$use.doInvoke(core.clj:5860)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at flatland.ordered.map$eval10898$loading__5569__auto____10899.invoke(map.clj:1)
	at flatland.ordered.map$eval10898.invokeStatic(map.clj:1)
	at flatland.ordered.map$eval10898.invoke(map.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clj_yaml.core$eval10892$loading__5569__auto____10893.invoke(core.clj:1)
	at clj_yaml.core$eval10892.invokeStatic(core.clj:1)
	at clj_yaml.core$eval10892.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at ring.middleware.format_params$eval10875$loading__5569__auto____10876.invoke(format_params.clj:1)
	at ring.middleware.format_params$eval10875.invokeStatic(format_params.clj:1)
	at ring.middleware.format_params$eval10875.invoke(format_params.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at ring.middleware.format$eval10869$loading__5569__auto____10870.invoke(format.clj:1)
	at ring.middleware.format$eval10869.invokeStatic(format.clj:1)
	at ring.middleware.format$eval10869.invoke(format.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at guestbook.middleware$eval10765$loading__5569__auto____10766.invoke(middleware.clj:1)
	at guestbook.middleware$eval10765.invokeStatic(middleware.clj:1)
	at guestbook.middleware$eval10765.invoke(middleware.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at guestbook.handler$eval218$loading__5569__auto____219.invoke(handler.clj:1)
	at guestbook.handler$eval218.invokeStatic(handler.clj:1)
	at guestbook.handler$eval218.invoke(handler.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at guestbook.core$eval212$loading__5569__auto____213.invoke(core.clj:1)
	at guestbook.core$eval212.invokeStatic(core.clj:1)
	at guestbook.core$eval212.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at user$eval3$loading__5569__auto____4.invoke(user.clj:1)
	at user$eval3.invokeStatic(user.clj:1)
	at user$eval3.invoke(user.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:359)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:355)
	at clojure.lang.RT.doInit(RT.java:475)
	at clojure.lang.RT.<clinit>(RT.java:331)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray
	at clojure.lang.Compiler$NewInstanceMethod.parse(Compiler.java:8206)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7798)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7678)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	... 244 more
```

**Comment by hiredgunhouse** [comment]
I have looked around and found this issue https://github.com/luminus-framework/luminus-template/issues/512 but in my case I don't have ~/.lein/profiles.clj file at all, I did in the past, so maybe something is cached somewhere, I don't know.

**Comment by yogthos** [comment]
It looks like you are getting some dependency conflict happening. You could try running `lein deps :tree` to see where it's coming from.

**Comment by hiredgunhouse** [comment]
Here's the output:
```
 [clojure-complete "0.2.5" :exclusions [[org.clojure/clojure]]]
 [com.h2database/h2 "1.4.192"]
 [compojure "1.5.1"]
   [clout "2.1.2"]
     [instaparse "1.4.0" :exclusions [[org.clojure/clojure]]]
   [medley "0.8.2"]
   [org.clojure/tools.macro "0.1.5"]
   [ring/ring-codec "1.0.1"]
   [ring/ring-core "1.5.0"]
     [clj-time "0.11.0"]
     [commons-fileupload "1.3.1"]
     [commons-io "2.5"]
     [crypto-equality "1.0.0"]
     [crypto-random "1.2.0"]
 [conman "0.6.2"]
   [com.carouselapps/to-jdbc-uri "0.5.0"]
   [com.layerware/hugsql "0.4.7"]
     [com.layerware/hugsql-adapter-clojure-java-jdbc "0.4.7"]
     [com.layerware/hugsql-core "0.4.7"]
       [com.layerware/hugsql-adapter "0.4.7"]
   [hikari-cp "1.7.4"]
     [com.zaxxer/HikariCP "2.5.1"]
     [org.tobereplaced/lettercase "1.0.0"]
     [prismatic/schema "1.0.4"]
   [org.clojure/java.jdbc "0.6.1"]
 [cprop "0.1.9"]
 [funcool/struct "1.0.0"]
   [funcool/cuerdas "0.7.2"]
 [luminus-immutant "0.2.2"]
   [org.immutant/web "2.1.5"]
     [org.immutant/core "2.1.5"]
     [org.projectodd.wunderboss/wunderboss-clojure "0.12.2"]
     [org.projectodd.wunderboss/wunderboss-web-undertow "0.12.2"]
       [io.undertow/undertow-core "1.3.23.Final"]
         [org.jboss.xnio/xnio-api "3.3.6.Final"]
         [org.jboss.xnio/xnio-nio "3.3.6.Final" :scope "runtime"]
       [io.undertow/undertow-servlet "1.3.23.Final"]
         [org.jboss.spec.javax.annotation/jboss-annotations-api_1.2_spec "1.0.0.Final"]
       [io.undertow/undertow-websockets-jsr "1.3.23.Final"]
       [org.projectodd.wunderboss/wunderboss-core "0.12.2"]
         [ch.qos.logback/logback-classic "1.1.3"]
           [ch.qos.logback/logback-core "1.1.3"]
         [org.jboss.logging/jboss-logging "3.2.1.Final"]
       [org.projectodd.wunderboss/wunderboss-web "0.12.2"]
         [org.jboss.spec.javax.servlet/jboss-servlet-api_3.1_spec "1.0.0.Final"]
         [org.jboss.spec.javax.websocket/jboss-websocket-api_1.1_spec "1.1.0.Final"]
 [luminus-migrations "0.2.8"]
   [migratus "0.8.32"]
     [org.clojure/java.classpath "0.2.3"]
 [luminus-nrepl "0.1.4"]
   [org.clojure/tools.nrepl "0.2.12"]
 [markdown-clj "0.9.90"]
 [metosin/ring-http-response "0.8.0"]
   [potemkin "0.4.3"]
     [clj-tuple "0.2.2"]
     [riddley "0.1.12"]
   [slingshot "0.12.2"]
 [mount "0.1.10"]
 [nrepl "0.8.3" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.cli "0.3.5"]
 [org.clojure/tools.logging "0.3.1"]
 [org.webjars.bower/tether "1.3.7"]
 [org.webjars/bootstrap "4.0.0-alpha.3"]
 [org.webjars/font-awesome "4.6.3"]
 [org.webjars/jquery "3.1.1"]
 [org.webjars/webjars-locator-jboss-vfs "0.1.0"]
   [org.webjars/webjars-locator-core "0.30"]
     [org.apache.commons/commons-compress "1.9"]
     [org.apache.commons/commons-lang3 "3.1"]
     [org.slf4j/slf4j-api "1.7.7"]
 [pjstadig/humane-test-output "0.8.1"]
 [prone "1.1.2"]
 [ring-middleware-format "0.7.0"]
   [cheshire "5.5.0"]
     [com.fasterxml.jackson.core/jackson-core "2.5.3"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
     [tigris "0.1.1"]
   [circleci/clj-yaml "0.5.5"]
     [org.flatland/ordered "1.5.3"]
       [org.flatland/useful "0.9.0"]
     [org.yaml/snakeyaml "1.13"]
   [clojure-msgpack "1.1.2"]
     [org.clojure/test.check "0.7.0"]
   [com.cognitect/transit-clj "0.8.285"]
     [com.cognitect/transit-java "0.8.311"]
       [org.msgpack/msgpack "0.6.10"]
         [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
         [org.javassist/javassist "3.18.1-GA"]
   [com.ibm.icu/icu4j "56.1"]
   [org.clojure/core.memoize "0.5.7"]
     [org.clojure/core.cache "0.6.4"]
       [org.clojure/data.priority-map "0.0.4"]
   [org.clojure/tools.reader "0.10.0"]
 [ring-webjars "0.1.1"]
   [org.webjars/webjars-locator "0.27"]
     [com.fasterxml.jackson.core/jackson-databind "2.3.3"]
       [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
 [ring/ring-defaults "0.2.1"]
   [javax.servlet/servlet-api "2.5"]
   [ring/ring-anti-forgery "1.0.1"]
   [ring/ring-headers "0.2.0"]
   [ring/ring-ssl "0.2.1"]
 [ring/ring-devel "1.5.0"]
   [clj-stacktrace "0.2.8"]
   [hiccup "1.0.5"]
   [ns-tracker "0.3.0"]
     [org.clojure/tools.namespace "0.2.10"]
 [ring/ring-mock "0.3.0"]
 [selmer "1.10.0"]
   [commons-codec "1.10"]
   [joda-time "2.9.3"]
   [json-html "0.3.9"]
     [hiccups "0.3.0"]
       [org.clojure/clojurescript "0.0-2069"]
         [com.google.javascript/closure-compiler "v20130603"]
           [args4j "2.0.16"]
           [com.google.code.findbugs/jsr305 "1.3.9"]
           [com.google.guava/guava "14.0.1"]
           [com.google.protobuf/protobuf-java "2.4.1"]
           [org.json/json "20090211"]
         [org.clojure/data.json "0.2.3"]
         [org.clojure/google-closure-library "0.0-20130212-95c19e7f0f5f"]
           [org.clojure/google-closure-library-third-party "0.0-20130212-95c19e7f0f5f"]
         [org.mozilla/rhino "1.7R4"]
```
Does anything seem odd to you?

**Comment by hiredgunhouse** [comment]
Should I maybe try to isolate the environment pollution and try Docker? I don't want to waste your time and I also want to move on reading your book :D

**Comment by yogthos** [comment]
Yeah, using a Docker image might be the easiest way to go. And it looks like the culprit might be

```
[ring-middleware-format "0.7.0"]
   ...
   [circleci/clj-yaml "0.5.5"]
     [org.flatland/ordered "1.5.3"]
 ```

The `ordered` library version doesn't work with the news JVM versions. You also might be able to fix the issue by adding a newer version of the library explicitly in the project `[org.flatland/ordered "1.5.9"]`.

**Comment by hiredgunhouse** [comment]
You were right, this fixed the problem. Thank you!
